obj-y				+= regsave.o
obj-$(CONFIG_ARM)		+= s2-arm.o pm-arm.o
obj-$(CONFIG_ARM64)		+= s2-arm64.o pm-arm.o
obj-$(CONFIG_BMIPS_GENERIC)	+= s2-mips.o s3-mips.o pm-mips.o
obj-$(CONFIG_BRCMSTB_XPT_HASH)	+= xpt_dma.o
